### ISSUE TITLE
PiT 25.2: RangeSlider int literals fail to compile with Vaadin 25.2

### ISSUE THREAD

**Issue by manolo** [vaadin/expo-flow#8]
### Description of the bug

`ComponentsView.java` uses int literals in `RangeSlider` and `RangeSliderValue` constructors:

```java
RangeSlider rangeSlider = new RangeSlider("Price range", 0, 1000);
rangeSlider.setValue(new RangeSliderValue(200, 800));
```

In Vaadin 25.2, `RangeSliderValue` constructor changed from `(double, double)` to `(Double, Double)`. Java does not auto-convert `int` to `Double` (wrapper), so the code fails to compile:

```
incompatible types: int cannot be converted to java.lang.Double
```

### Fix

Use double literals (`0.0`, `1000.0`, `200.0`, `800.0`) instead of int. This is compatible with both 25.1 and 25.2.

### Versions

- Vaadin / Flow version: 25.2.0-alpha3
- Works with: 25.1.3
